name: Test the Action

on:
  - push
  - pull_request

jobs:
  action-in-action:
    name: Action in action
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Get Keyvault Secrets
        id: get-secret
        uses: ./
        with:
          keyvault: ${{ secrets.AZURE_KEYVAULT_NAME }}
          secrets: ${{ secrets.AZURE_SECRET_NAME }}

      - name: What is the secret?
        run: echo ${{ steps.get-secret.outputs[secrets.AZURE_SECRET_NAME] }}